name: 'gtd_warehouse'
version: '1.0.0'
config-version: 2

profile: 'gtd_profile'

# dbt where to find files
model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

# --- MODEL CONFIGURATION ---
models:
  gtd_warehouse:
    # 1. Staging Layer: Clean data
    staging:
      +materialized: view
      +schema: staging
    
    # 2. Warehouse Layer: Final data
    warehouse:
      +materialized: table
      +schema: warehouse

    # 3. Marts Layer: Business Ready Data
    marts:
      +materialized: table
      +schema: marts