version: 2

sources:
  - name: gtd_source
    database: airflow
    schema: public
    tables:
      - name: raw_gtd
        description: "Raw terrorist attack data loaded from MinIO"
      
      # --- Bagian ini yang WAJIB ada untuk mengatasi error ---
      - name: raw_property_index
        description: "OECD Real House Price Index loaded from API"